### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by StarostinVlad** [samthesuperhero/clourfid#1]
Запускал на ubuntu, выдает Error during estabilish connection

**Comment by samthesuperhero** [comment]
Добрый день, скиньте пожалуйста сюда все логи которые у вас появились в папке которую вы настроили в конфиге в [параметре](https://github.com/samthesuperhero/clourfid/blob/master/clou.conf.txt) "log-dir"

**Comment by StarostinVlad** [comment]
эту проблему уже решили, но теперь он ругается следующим образом
![Аннотация (1)](https://user-images.githubusercontent.com/48319581/72807772-2c425a00-3c69-11ea-979f-fad474f4c008.png)

**Comment by StarostinVlad** [comment]
также заметил что в clouweb 24 строка захардкожен путь к файлу, это опечатка или так и задумывалось?

**Comment by samthesuperhero** [comment]
> , но теперь он ругается следующим образом

не очень понимаю вывод на вашем скриншоте, видимо он неполный, т.к. строка 148 это (как минимум в [мастере](https://github.com/samthesuperhero/clourfid/blob/5ac0bf9c37265e8accc43dd03c6d6253e0d09474/clouweb.py#L148)):

`        return response_payload`

- но это в принципе не очень критично, учитывая где он подыхает могу сказать что проблема с конфигом.

> также заметил что в clouweb 24 строка захардкожен путь к файлу, это опечатка или так и задумывалось?

и да, расположение и имя конфига для WSGI приложения фиксированное, просто папка в мастере clouweb.py кривая (/usr/share/dev/clouweb/clou.conf), это ошибка, исправлю перезалью в пакете со следующими фиксами, (наверное WSGI должен будет читать путь к конфигу через переменную окружения, отражу )

**быстрый патч**: прос замените абсолютный путь на ваш, это просто переменная, т.е. в строке 24: conf_file_name = "/ваш/абсолютный/путь/clou.conf"

**Comment by StarostinVlad** [comment]
данную проблему решил, оказалось что проблема была в uswgi он по умолчанию под второй питон запускался, но теперь возникла проблема, не получается подключиться к ридеру

**Comment by samthesuperhero** [comment]
Скиньте сюда все логи пожалуйста! Желательно файлами, не скриншотами!

**Comment by StarostinVlad** [comment]
[cloucon-IN-2020-01-22-14+0300.log](https://github.com/samthesuperhero/clourfid/files/4096782/cloucon-IN-2020-01-22-14%2B0300.log)
Вот

**Comment by samthesuperhero** [comment]
**Сможете прислать конфиг?** Какая версия интерпретатора Python? Ошибка соединения судя по логу, но `socket` вообще в случае ошибок на сети почти не падает, скорее это либо что-то с параметрами передаваемыми в методы, либо с правами в linux.

**Comment by kingofclowns123** [comment]
Добрый день

[clou.conf.txt](https://github.com/samthesuperhero/clourfid/files/4096975/clou.conf.txt)

**Comment by samthesuperhero** [comment]
Смотрите что в логе:
`[ 22.01.2020 14:08:44.346012+0300 ] > Expecting that reader is in server mode`
`[ 22.01.2020 14:08:44.346369+0300 ] > Connecting to 192.168.0.116:10101`

в конфиге же у вас:
`    "readers-list": [`
`        "IN"`
`    ],`
`    "IN": {`
`        "reader-mode": "client",`
`        "host": "",`
`        "port": 10101, `

Лог пишет что "Expecting that reader is in **server** mode" и затем он пишет что пытается подключиться `Connecting to 192.168.0.116:10101`,

то есть процесс читает другой конфиг, не тот который вы мне прислали. Т.к. если ридер в клиентском режиме что должно быть отражено в конфиге как `"reader-mode": "client"` то в логе он напишет `Listening for incoming connection at` и номер порта.

Можете прислать тот конфиг который использует процесс? Хочу проверить что в конфиге у вас тип порта это число а тип хоста это строка. Других причин с ходу не вижу, если причина в другом то будем дебагить более глубоко!

**Comment by kingofclowns123** [comment]
В общщем удалось подключиться в режиме сервера, в режиме клиента не получилось, но теперь ридер скидывает любой коннект даже от их собственной ПО Hopeland RFID manager 2.25

**Comment by kingofclowns123** [comment]
[cloucon-IN-2020-01-22-15+0300.log](https://github.com/samthesuperhero/clourfid/files/4097406/cloucon-IN-2020-01-22-15%2B0300.log)
[clou.conf.txt](https://github.com/samthesuperhero/clourfid/files/4097407/clou.conf.txt)

**Comment by samthesuperhero** [comment]
> В общем удалось подключиться в режиме сервера, в режиме клиента не получилось

там на их ридерах есть переключение режима; ну и проверьте файрвол на всякий случай если что-то стоит, проброшены ли порты;

> но теперь ридер скидывает любой коннект

у меня есть определенный опыт.. Там есть несколько вариантов, т.к. настройки достаточно замороченые; еслисможете прислать лог от момента запуска процесса до момента когда ридер скидывает могу глянуть, лог пишет в том числе сырые данные от ридера, возможно он что-то пытается сообщить перед тем как скидывает

> cloucon-IN-2020-01-22-15+0300.log
> clou.conf.txt

Вижу что ридер просто не коннектит

**Comment by kingofclowns123** [comment]
Снова вопрос, с коннектом разобрались. Хотелось бы уточнить, что значит "check Clou Protocol specification"? И где именно проверять это? https://github.com/samthesuperhero/clourfid/blob/master/cmdref/OP_READ_EPC_TAG.json.txt

**Comment by samthesuperhero** [comment]
Если конкретный вопрос есть могу здесь ответить, если в общем - то вам надо запросить у Hopeland документацию на протокол, в которой есть все низкоуровневые определения.

**Comment by StarostinVlad** [comment]
заметили такой момент, ридер не переходит в режим чтения меток, в чем может быть дело? через китайскую софтину все работает

**Comment by samthesuperhero** [comment]
Если вам нужно предавать в сканнер какие-то параметры которые не отражены в API, я готов доработать.

**Comment by samthesuperhero** [comment]
> заметили такой момент, ридер не переходит в режим чтения меток, в чем может быть дело?
> через китайскую софтину все работает

вы хотите непрерывный режим ? тогда установите `val` в `iscont` в значение 1. Будет постоянно шарашить. Или что-то другое?

**Comment by kingofclowns123** [comment]
Постараюсь конкретизировать, когда отправляем запрос на чтение в API, но все время выходит в ответе:
{
    "msid": "OP_READ_EPC_TAG",
    "mtyp": "TYPE_CONF_OPERATE",
    "init": "INIT_BY_USER",
    "prms": {
        "startres": {
            "pid": "M",
            "is-fixed-len": true,
            "type": "U8",
            "len": 1,
            "val": 2,
            "is-res-field": true,
            "OK-value": 0,
            "text-meaning": {
                "0": "Configure successfully",
                "1": "Antenna port parameter error",
                "2": "Select read parameter error",
                "3": "TID read parameter error",
                "4": "User data area read parameter error",
                "5": "Retention area read parameter error",
                "6": "Other parameter error"
            }
        }
    }
}
Мы не можем подобрать параметр "val" в "selectread" перепробовали даже поставить скрипт на перебор от 0-255(как мы поняли это максимум). Нигде не нашли описания данного параметра.

**Comment by kingofclowns123** [comment]
[Ответ.txt](https://github.com/samthesuperhero/clourfid/files/4102606/default.txt)
В удобно читаемом виде

**Comment by samthesuperhero** [comment]
А вы уверены что вам нужен `selectread`? Это опциональный параметр его вообще можно не указывать.

Обязательные только параметры для которых `pid` = `M`.

Вообще это параметр для того чтобы запросить у ридера конкретные биты памяти метки (по стандарту кроме EPC и TID может быть кастомная память). Ну и это параметр переменной длинны.

А что вы хотите точно получить?

**Comment by kingofclowns123** [comment]
Все ожило, спасибо. Невнимательность стоила пол для...

**Comment by samthesuperhero** [comment]
Закрываем тикет?

**Comment by kingofclowns123** [comment]
Да, можно
